#spring.banner.image.location=logo.jpg:
spring:
  banner:
    image:
      location: classpath:logo.jpg

guru:
  username: ymluser-default
  password: ymlpassword-defualt
server:
  port: 8080
---
spring:
  profiles: de
guru:
  username: ymluser-de
  password: ymlpassword-de
---
spring:
  profiles: en
guru:
  username: ymluser-en
  password: ymlpassword-en
